### ISSUE TITLE
Support Aspnet core 3.0 with System.Text.Json 

### ISSUE THREAD

**Issue by badre429** [Breeze/breeze.server.net#86]
dotnet core 3.0 is RC released

**Comment by steveschmitt** [comment]
Thanks.  We'll look at the changes needed for System.Text.Json.

**Comment by ganySA** [comment]
I tried some time ago using .net core 3.0 with the current library and had quite a few issues with the metadata that was being generated - could be related to this.

**Comment by ganySA** [comment]
Do you guys have an ETA on this? i believe core3 has significant performance improvements over 2

**Comment by ganySA** [comment]
bump!

**Comment by ganySA** [comment]
bump!

**Comment by ganySA** [comment]
How about a black friday release *wink* *wink*

**Comment by jtraband** [comment]
Ok, I just released new '3.x' versions of Breeze.AspNetCore.NetCore, Breeze.Core, Breeze.Persistence and Breeze.Persistence.EFcore that supports .NET Core 3/ASP.NET Core 3 and EF Core 3. To support older .NET Core 2/EF Core 2 apps you will still need to install the '1.x' versions of these same nugets.

Note: we are still using Newtonsoft instead of System.Text.Json because the System.Text.Json lib does not yet support recursive graphs or refs.  ( This is also Microsoft's advice ).
