### ISSUE TITLE
metadata generation

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze.server.net#95]
Hello 
I'm going to migrate a .net 4.6 project to .net core and I wanted to know if the .net core version of breeze has all the features already implemented in the .net framework version ? 

In the sample the metadata is generated to a json file. Is it better practice than having a dedicated endpoint in the controller to return metadata ?

**Comment by steveschmitt** [comment]
Either way can be used.  Generating the metadata in advance means that it can be built into the application, so the app doesn't have to do a separate call to the server to retrieve metadata during startup.

In our TypeScript applications, we generate the metadata to a json file anyway, because we use it to generate the TypeScript classes for our entity model.  Then, since we've generated the json, it is easy to include it in the app.

**Comment by graphicsxp** [comment]
Steve, thanks for the insight ! 
What about .net core version of breeze server then ? Does it have all the features of the .net version ?

I gave it a try but I had to migrate to 3.1 since there does not seem to be a version of breeze for 3.0. Will breeze follow LTS versions only  or also other versions ?

**Comment by steveschmitt** [comment]
There are some differences:
1. The metadata produced by the .NET Core version is in the Breeze native format.  In .NET Framework, the metadata was in a CSDL format (produced by EF), which was translated by the client.
2. The .NET Core version does not support the OData query syntax.  It supports only the JSON query syntax, so the client will use the UriBuilderJsonAdapter instead of the UriBuilderODataAdapter.

We support .NET Core 2.0 and 3.1 now, and we plan to support the LTS versions going forward.

**Comment by graphicsxp** [comment]
Thanks for that information, it's very useful. I'm not familiar with the JSON query syntax. I've been using mostly the OData query syntax, but that happened under the hood using breeze query language in JavaScript anyways. Should I care ? I guess I just need have to specify the JsonAdapter and keep coding as before, right ?

**Comment by jtraband** [comment]
Yep, just specify the UriBuilderJsonAdapter;, none of your client code needs to change.

**Comment by graphicsxp** [comment]
I just took a look at `adapter-uri-builder-json.ts` . How does the expand, orderby, select, etc... operations work with this adapter ?  Do you an example somewhere ?

**Comment by jtraband** [comment]
On the client, no changes are needed; you still construct your queries exactly as you did with earlier version.  On the server, you will need a .NET Core 2/3 project that uses the new Dlls.  There is an example [here](https://github.com/Breeze/northwind-core-ng-demo/blob/master/STEPS-Server-Core3.md) -- https://github.com/Breeze/northwind-core-ng-demo/blob/master/STEPS-Server-Core3.md

**Comment by graphicsxp** [comment]
Thanks Jay, I alreaday been through this sample to setup my .net core project. I'm going to test from the client with UriBuilderJsonAdapter. If you say it  makes no differences codewise then I'm good to go. 
I also like the fact you will support future LTS versions, that's great news !
Thanks !
