### ISSUE TITLE
Fail to insert when using ValueGeneratedOnAdd  

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze.server.net#98]
We use ValueGeneratedOnAdd on our Primary Key and when we create a new entity the insert fails because there is no Id.

This is because of this code in breeze EFPersistenceManager : 

```
        if (entityInfo.AutoGeneratedKey.AutoGeneratedKeyType == AutoGeneratedKeyType.Identity) {
          // HACK: because EF Core will not allow inserts to an Identity column where a value exists on incoming entity.
          entry.Property(propName).IsTemporary = true;
        }      
```

When the IsTemporary value is set to true, the guid is reset to 0 and the entity is added to the context without an Id. 

If we comment this line, it works fine. Could you explain this hack ? Should we keep it ?

**Comment by graphicsxp** [comment]
Hello Steve.

That is not correct. 

ValueGeneratedOnAd means the value is generated for new entities. It "can" be generated by the database, but it doesn't have to.

In my case the primary key is also a foreign key to another table.  So I rely o. EF to

**Comment by steveschmitt** [comment]
I think I see.  First I will try to explain the reason for the "hack" code above.  

When the Breeze client creates a new entity, or a tree of new entities, it needs to generate IDs for those entities to establish the foreign-key relationships.  If (according to the metadata) it knows that these entities have server-generated keys, it creates temporary IDs.  

For the common case of integer keys that are generated in the database by an IDENTITY column, the Breeze client generates negative numbers for the temporary IDs.  Then on the server, these IDs would be replaced by the real IDs from the database, and returned to the client with a mapping of temporary ID to real ID.  The Breeze client would update its entity cache so the entities have the real IDs.

The problem is that, when there is an IDENTITY column in the database, the database won't let EF can't save an entity with an already-assigned key.  The `IsTemporary` flag is a signal that the temporary ID value should be removed before saving.

I think the problem is that the `AutoGeneratedKeyType.Identity` is being interpreted as a database-generated key, and you are using it as a code-generated key. 

@jtraband Is there a different `AutoGeneratedKeyType` value that would be more appropriate for this case?  Or is there some other way for Breeze distinguish between database-generated and server-code-generated keys?

**Comment by graphicsxp** [comment]
Yes, I understand that breeze has to generate IDs and that's totally fine. 


I don't use integer for primary keys, only GUIDS and I have not faced this problem you are describing. If I comment the "hack"  code, everything works just fine, IDs are generated by breeze, EF generates new IDs and they are then returned and merged into the client entities. By the way I have tried using NEWID( ) in the SQL Server tables and it works fine too. 

Maybe the problem you are describing only occurs with INTEGER PKs...

**Comment by steveschmitt** [comment]
I think the problem is that AutoGeneratedKeyType is being set to AutoGeneratedKeyType.**Identity** when it should be AutoGeneratedKeyType.**KeyGenerator**

**Comment by GioviQ** [comment]
if the key is a Guid IsTemporary have be set to true only if current key value is Guid.Empty

With current implementation if Guid key has a value different from Guid.Empty a SQLException is raised (Insert failed because ID is NULL).

AutoGeneratedKeyType.Identity in Breeze.Sharp is used for both int and Guid keys. AutoGeneratedKeyType.KeyGenerator is never used.

EF Core 6 for default Guid key does not set newid() in db.

**Comment by GioviQ** [comment]
In fact a similar logic used in https://github.com/GioviQ/breeze.sharp/blob/master/Breeze.Sharp/EntityManager.cs#L1209 to decide whether to generate an id, should be used to decide if a key has a temporary value.
